name: model-RH_application

on: [push]

jobs:

  run:

    runs-on: [ubuntu-latest]

    container: docker://dvcorg/cml-py3:latest

    steps:

      - uses: actions/checkout@v2

      - name: cml_run

        env:

          repo_token: ${{ secrets.GITHUB_TOKEN }}

        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          Model_Projet_22052023_Final_V3_Rachid.ipynb
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
